---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: auto-scalar-cluster
  region: us-east-2
availabilityZones:
- us-east-2a
- us-east-2b
managedNodeGroups:
- name: managed-nodes
  labels:
    role: managed-nodes
  instanceType: t2.micro
  minSize: 1
  maxSize: 10
  desiredCapacity: 1
  volumeSize: 20