apiVersion: v1
kind: Pod
metadata:
  name: frontend
spec:
  containers:
  - name: php-redis
    image: gcr.io/google_samples/gb-frontend:v5
    env:
     - name: php-redis
       value: "dns"
    resources:
    ports:
      - containerPort: 80
