apiVersion: v1
kind: Pod
metadata:
  name: redis-leader
  labels:
    app: redis
    role: leader
    tier: backend
spec:
  containers:
  - name: leader
    image: "docker.io/redis:6.0.5"
    ports:
      - containerPort: 6379
