apiVersion: v1
kind: Pod
metadata:
  name: redis-follower
  labels:
    app: redis
    role: follower
    tier: backend

spec:
  containers:
  - name: follower
    image: gcr.io/google_samples/gb-redis-follower:v2
    resources:
    ports:
      - containerPort: 6379
