apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster
  region: us-east-2

nodeGroups:
  - name: ng-1
    instanceType: t2.small
    desiredCapacity: 1
    minSize: 1
    maxSize: 10
    volumeSize: 5
    ssh:
      publicKeyPath: ~/.ssh/id_rsa.pub
