apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.service.Service_name }}
  labels:
    app: {{.Values.service.app}}
spec:
  selector:
    matchLabels:
      app: {{ .Values.service.app }}
      tier: {{ .Values.service.tier }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Values.service.app }}
        tier: {{ .Values.service.tier }}
    spec:
      containers:
      - image: {{.Values.containers.image}}
        name: {{.Values.containers.name}}
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: {{.Values.containers.port}}
          name: {{.Values.containers.name}}
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: {{.Values.PersistentVolumeClaim.claimName}}